################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/en"
weight = 1
[en.params]
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Services / Products"
footer_menu_right = "Support"
footer_content = "Smarter Software for Smarter Systems."

################################### Deutsch language #####################################
[de]
languageName = "DE"
languageCode = "de-DE"
contentDir = "content/de"
weight = 2
[de.params]
########### footer content ##########
footer_menu_left = "Firma"
footer_menu_middle = "Leistungen / Produkte"
footer_menu_right = "Support"
# footer_content = "Lorem ipsum dolor sit amet, consectetur elit consjat tristique eget amet."
footer_content = "Smarter Software for Smarter Systems."


